name: Embed code in README

on: 
  push:
    paths:
      - 'README.md'
      - 'custom_require_package_loader.lua'
      - '.github/*'
    branches: 
      - 'master'
  pull_request:
    paths:
      - 'README.md'
      - 'custom_require_package_loader.lua'
      - '.github/*'
    branches: 
      - 'master'

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "synchronizing Readme"
          silent: true
