name: Embed code in README

on: 
  workflow_dispatch:
  push:
    paths:
      - 'README.md'
      - 'custom_require_package_loader.lua'
      - '.github/workflows/Embed_code_in_README.yml'
    branches: 
      - 'master'

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          
      
      
      - uses: technology-studio-forks/markdown-embed-code@v1.1.2 # tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "synchronizing Readme"
          silent: true
